fixed model try catch and also got every model to 100% coverage
401n14/midTerm pull request #19
Opened 2019-12-03 23:46 UTC by Martinbalke

2019-12-04 00:16 UTC, mts513 commented on __tests__/database.test.js
> +  message: 'Wow this app is cool',
LOL! Very true =)

2019-12-04 00:20 UTC, CaptainMorganCodes reviewed
What was the reason for removing the try/catch in create, read, & delete? Are we accounting for this elsewhere? Or is it built in by mongoose?

2019-12-04 03:38 UTC, james-ad requested changes

2019-12-04 03:38 UTC, james-ad commented on __tests__/database.test.js
> +const chat = new Chat;
Does this need to be `new Chat()`?

2019-12-04 03:38 UTC, james-ad commented on __tests__/database.test.js
> +const chat = new Chat;
```suggestion
const chat = new Chat();
```

2019-12-04 03:38 UTC, james-ad commented on __tests__/database.test.js
> +const connection = new Connection;
```suggestion
const connection = new Connection;
```
```suggestion
const connection = new Connection;
```
```suggestion
const connection = new Connection();
```

2019-12-05 02:54 UTC, CaptainMorganCodes approved these changes

2019-12-05 02:57 UTC, james-ad approved these changes

2019-12-05 02:58 UTC, merged